volumes:
  db:

services:
  gym-pass-api-pg:
    container_name: gym-pass-api-pg
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_DATABASE: gym-pass
    ports:
      - 5432:5432
    volumes:
      - db:/bitnami/postgresql
